#!/bin/sh

if [ "$#" -eq 0 ]
then
  echo "Must supply path to archive files"
  exit 1
fi

target="$1"
flag="strict"

if [ "$#" -gt 1 ]
then
  flag="$1"
  target="$2"
fi

native="$target"

osname=`uname -s | sed -e 's/_NT-.*$/_NT/; s/^MINGW[0-9]*/CYGWIN/'`
if [ "$osname" = "CYGWIN_NT" -a -x /bin/cygpath ]
then
  target=`cygpath -w "$target"`
fi

target=${target%/}
native=${native%/}

deleteCitations() {
  inp="$1"
  pmidlist=.TO-REPORT
  delenda=.TO-DELETE
  xtract -input "$inp" -pattern DeleteCitation -block PMID -tab "\n" -sep "." -element "PMID" |
  sort | uniq > $pmidlist
  cat "$pmidlist" |
  rchive -trie -gzip |
  sort | uniq > $delenda
  if [ -s $delenda ]
  then
    (cd "$native" && xargs rm -f) < $delenda
  fi
  if [ -s $pmidlist ]
  then
    cat "$pmidlist" >> "$native/deleted.uid"
  fi
  rm $pmidlist
  rm $delenda
}

for fl in *.xml.gz
do
  base=${fl%.xml.gz}
  if [ -f "$base.snt" ]
  then
    continue
  fi
  echo "$base"
  gunzip -c "$fl" > "$base.xml"
  rchive -gzip -flag "$flag" -input "$base.xml" -archive "$target" \
    -index MedlineCitation/PMID^Version -pattern PubmedArticle
  deleteCitations "$base.xml"
  touch "$base.snt"
  rm "$base.xml"
done
